[package]
name = "locha-p2p"
version = "0.1.0"
authors = ["Jean Pierre Dudey <me@jeandudey.tech>"]
edition = "2018"

[workspace]
members = ["protocols/chat"]

[dependencies]
locha-p2p-chat = { version = "0.1", path = "protocols/chat" }