[package]
name = "miniupnpc-sys"
version = "0.1.0"
authors = ["Locha Mesh Developers <contact@locha.io>"]
edition = "2018"
license = "Apache-2.0"
build = "build.rs"

[build-dependencies]
git2 = "0.13"
cc = "1"
bindgen = "0.55"