on: push

name: Continuous integration (MUSL)

jobs:
  ci:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust:
          - stable

    steps:
      - uses: actions/checkout@v2
      - run: sudo apt-get install musl-tools

      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: ${{ matrix.rust }}
          override: true
          target: x86_64-unknown-linux-musl

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --target x86_64-unknown-linux-musl

      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: --target x86_64-unknown-linux-musl
